name: qcafe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  get_storage: ^2.0.3
  pin_code_fields: ^7.3.0
  flutter_slidable: ^1.2.0
  table_calendar: ^3.0.5
  floating_bottom_navigation_bar: ^1.5.2
  google_maps_flutter: ^2.1.3
  # geolocator: ^8.2.0
  geocoding: ^2.0.4
  persistent_bottom_nav_bar: ^4.0.2
  eva_icons_flutter: ^3.1.0
  google_maps_place_picker: ^2.1.0-nullsafety.3
  flutter_countdown_timer: ^4.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  im_animations: ^0.1.2
  flutter_rating_bar: ^4.0.1
dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
       


